config/routes.rb
Rails.application.routes.draw do
  devise_for :mentors

  resources :mentors, only: [:index, :show] do
   resources :episodes
   resources :posts
  end

  authenticated :mentor do
   root 'mentors#dashboard', as: "authenticated_root"
  end

  resources :contacts, only: [:new, :create]
  resources :how, only: [:index]

  resources :hubs do
   collection do
     get 'search'
   end
  end

  root 'welcome#index'
  get '/how' => 'how#index'
  get '/schedules' => 'schedules#index'
end

app/models/episode.rb
class Episode < ActiveRecord::Base
  belongs_to :mentor

  has_attached_file :episode_thumbnail, :styles => { :large => "1000x1000#", :medium => "550x550#" }
  validates_attachment_content_type :episode_thumbnail, :content_type => /\Aimage\/.*\Z/

  has_attached_file :mp3
  validates_attachment_content_type :mp3, :content_type => { :content_type => ["audio/mpeg", "audio/mp3"]}, :file_name => { :matches => [/mp3\z/] }

 extend FriendlyId
 friendly_id :title, use: :slugged

end

app/models/mentor.rb
class Mentor < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_many :episodes
  belongs_to :category
  has_many :posts

  has_attached_file :thumbnail, :styles => { :large => "1000x1000#", :medium => "550x550#" }
  validates_attachment_content_type :thumbnail, :content_type => /\Aimage\/.*\Z/

 extend FriendlyId
 friendly_id :title, use: :slugged
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
   devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:email, :password,
   :password_confirmation, :title, :thumbnail, :category_id )}
 
   devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:email, :password,
   :password_confirmation, :current_password, :title, :description, :blog, :facebook, :twitter, :linkedin, :thumbnail, :category_id )}
  end

end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController
 before_action :authenticate_mentor!, except: [:show]
 before_filter :require_permission
 before_action :find_mentor
 before_action :find_episode, only: [:show, :edit, :update, :destroy]

 def new
  @episode =@mentor.episodes.new
 end

 def create
  @episode = @mentor.episodes.new episode_params
  if episode.save
   redirect_to mentor_episode_path(@mentor, @episode)
  else
   render 'new'
  end
 end 

 def show
  @episode = Episode.friendly.where(mentor_id: @mentor.order("created_at desc").limit(5).reject { |e| e.id ==@episode.id}  
 end

 def edit
 end

 def update
  if @episode.update episode_params
   redirect_to mentor_episode_path(@mentor, @episode), notice:"Episode was successfully updated!"
  else
   render 'edit'  
  end
 end

 def destroy
  @episode.destroy
  redirect_to root_path
 end

 private
 def episode_params
  params.require(:episode).permit(:title, :description, :episode_thumbnail, :mp3, :slug)
 end

 def find_mentor
  @mentor = mentor.friendly.find(params[:mentor_id])
 end

 def find_episode
  @episode = Episode.friendly.find(params[:id])
 end

 def require_permission
  @mentor = mentor.find(params[:mentor_id])
  if current_mentor != @mentor
   redirect_to root_path, notice: "Please sign up with the right credentials to view that post."
  end
 end

end

app/controllers/how_controller.rb
class HowController < ApplicationController
 def index
 end
end

app/controllers/mentors_controller.rb
class MentorsController < ApplicationController
 before_action :find_mentor, only: [:show, :dashboard]
 before_action :find_episode, only: [:index, :show, :dashboard]

 def index
   if params[:category].blank?
     @mentors = Mentor.all.order("created_at desc").paginate(:page => params[:page], :per_page => 12)
   else
     @category_id = Category.find_by(name: params[:category]).id
     @mentors = Mentor.where(category_id: @category_id).order("created_at desc").paginate(:page => params[:page], :per_page => 12)
   end
 end

 def show
 end

 def dashboard 
 end

 private
 def find_episode
  @episodes = Episode.friendly.where(mentor_id: @mentor).order("created_at desc").paginate(:page => params[:page], :per_page => 5)
 end

 def find_mentor
  if params[:id].nil?
    @mentor = current_mentor
  else
    @mentor = Mentor.friendly.find(params[:id])
  end
 end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
 def index

 end

end

app/helpers/application_helper.rb
module ApplicationHelper
 class HTMLwithPygments < Redcarpet::Render::HTML
  def block_code(code, language)
   Pygments.highlight(code, lexer: language)
  end
 end

 def markdown(content)
  renderer = HTMLwithPygments.new(hard_wrap: true, filter_html:true)
  options = {
   autolink: true,
   no_intra_emphasis: true,
   disable_indented_code_blocks: true,
   fenced_code_blocks: true,
   strikethrough: true,
   superscript: true
  }
  Redcarpet::Markdown.new(renderer,options).render(content).html_safe
 end

end

app/helpers/episodes_helper.rb
module EpisodesHelper
end

app/helpers/how_helper.rb
module HowHelper
end

app/helpers/mentors_helper.rb
module MentorsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/contacts/create.html.erb
<h1 id="page_title">Say Hello!</h1>
<div class="skinny_wrapper wrapper_padding">
 <h1> Thank you for your message!</h1>
 <p> We will get back you shortly...</p>
</div>








<%= render 'layouts/footer' %>

app/views/contacts/new.html.erb
<h1 id="page_title">Say Hello!</h1>
 <div class="skinny_wrapper wrapper_padding">
  <%= form_for @contact do |f| %>
  <%= f.label :name %> <br>
  <%= f.text_field :name, required: true %>
  <br>

  <%= f.label :email %> <br>
  <%= f.email_field :email, required: true %>

  <br>

  <%= f.label :message %> <br>
  <%= f.text_area :message, as: :text %>

  <div class="hidden">
  <%= f.label :nickname %> <br>
  <%= f.text_field :nickname, hint: 'leave this alone' %>
  </div>
 <br/><br/>
  <%= f.submit 'Send Message', class:"button button_highlight button_block" %>
  <%end %>
 </div>
<%= render 'layouts/footer' %>

app/views/episodes/_form.html.erb
 <%=form_for ([@mentor, @episode]) do |f| %>
 <div class="field">
  <%= f.label :title %> <br>
  <%= f.text_field :title %>
 </div>

 <div class="field">
  <%= f.label :description %> <br>
  <%= f.text_area :description%>
 </div>

 <div class="field">
  <%= f.label :episode_thumbnail %> <br>
  <%= f.file_field :episode_thumbnail, class: "button button_white button_block"%>
 </div>

 <div class="field">
  <%= f.label :mp3 %> <br>
  <%= f.file_field :mp3, class: "button button_white button_block" %>
 </div>

  <%= f.submit class:"button button_highlight button_block" %>
 <% end %>

app/views/episodes/edit.html.erb
   <div id="podcast_show">
   <div id="show_banner">
    <div class="wrapper_skinny">
       <h1><%= @mentor.title %> Dashboard</h1>
    </div>
   </div>
   <div id="links">
     <div class="wrapper_skinny">
      <ul>
        <li><%= link_to "Episodes", root_path %></li>
        <li><%= link_to "New Episode", new_mentor_episode_path(@mentor, episode), class: "current" %></li>
        <li><%= link_to "Account Settings", edit_mentor_registration_path %></li>
        <li><%= link_to "View Mentor", mentor_path(current_mentor) %></li>
      </ul>
     </div>
    </div>

<div id="form">
 <div class="wrapper_skinny">
  <%= render 'form' %>
 </div>
</div>

app/views/episodes/new.html.erb
 <div id="podcast_show">
   <div id="show_banner">
    <div class="wrapper_skinny">
       <h1><%= @mentor.title %> Dashboard</h1>
    </div>
   </div>
   <div id="links">
     <div class="wrapper_skinny">
      <ul>
        <li><%= link_to "Episodes", root_path %></li>
        <li><%= link_to "New Episode", new_mentor_episode_path(@mentor, episode), class: "current" %></li>
        <li><%= link_to "Account Settings", edit_mentor_registration_path %></li>
        <li><%= link_to "View Mentor", mentor_path(current_mentor) %></li>
      </ul>
     </div>
    </div>

<div id="form">
 <div class="wrapper_skinny">
  <%= render 'form' %>
 </div>
</div>

app/views/episodes/show.html.erb
    <div id="podcast_show">
     <div id="show_banner">
     	<div class="wrapper_skinny">
         <h1><%= @mentor.title %></h1>
               <p class="description"><%= @mentor.description %></p>
               <% unless @mentor.blog.blank? %>
                <a href="<%= @mentor.blog %>" class="subscribe_link">blog</a>
               <% end %>

               <% unless @mentor.facebook.blank? %>
                <a href="<%= @mentor.facebook %>" class="subscribe_link">facebook</a>
               <% end %>

               <% unless @mentor.twitter.blank? %>
                <a href="<%= @mentor.twitter %>" class="subscribe_link">twitter</a>
               <% end %>

               <% unless @mentor.linkedin.blank? %>
                <a href="<%= @mentor.linkedin %>" class="subscribe_link">linkedin</a>
               <% end %>
     	</div>      
     </div>
     <div id="breadcrumb">
       <%= link_to mentors_path do %>
       	All podcasts
       	<span>/</span> 
       <%= link_to @mentor.title, mentor_path(@mentor) %>
        <span>/</span>
        <%=@episode.title %>
       <% end %>
     </div>

     <div id="episode_content">
     	<div class="wrapper_skinny">
          <%= image_tag @episode.episode_thumbnail.url(:medium), class="current_episode_thumbnail" %> 
          <h2><%=@episode.title %></h2>
          <p class="description">
              <%=@episode.description %> 
          </p>
          <div id="jquery_jplayer_1" class="jp-jplayer"></div>
<div id="jp_container_1" class="jp-audio">
  <div class="jp-type-single">
    <div class="jp-gui jp-interface">

      <ul class="jp-controls">
      	<li> <a href="javascript:;" class="jp-play" tabindex="1">&#61515</a></li>
      	<li> <a href="javascript:;" class="jp-pause" tabindex="1">&#61516</a></li>
        <li> <a href="javascript:;" class="jp-mute" tabindex="1" title="mute">&#61480</a></li>
        <li> <a href="javascript:;" class="jp-unmute" tabindex="1" title="unmute">&#61478</a></li>
      </ul>

        <div class="jp-progress">
          <div class="jp-seek-bar">
            <div class="jp-play-bar"></div>
          </div>
        </div>

        <div class="jp-time-holder">
           <div class="jp-current-time"></div>
        </div>

        <div class="jp-volume-bar">
           <div class="jp-volume-bar-value"></div>
        </div>

    <div class="jp-no-solution">
      <span>Update Required</span>
      To play the media you will need to either update your browser to a recent version or update your <a href="http://get.adobe.com/flashplayer/" target="_blank">Flash plugin</a>.
    </div>
  </div>
</div>
     	</div>
     </div>	 

     <div id="episodes">
        <div class="wrapper_skinny">
          <ul class="cf">
           <% @episodes.each do |episode| %> 
            <li class="cf">
              <div class="episode_thumbnail">
                 <a href="episode.html">
                  <%= image_tag episode.episode_thumbnail.url(:medium) %>
                 </a>
              </div>
              <div class="episode_overview">
                <h2><%= link_to episode.title, mentor_episode_path(@mentor, episode) %></h2>
                 <p class="description">
                 <% truncate(episode.description, length: 160) %>
                 </p>     
              </div>	
            </li>
          <% end %>
          </ul>
        </div>
     </div>
        <hr>
        <%= render 'disqus' %> 
    </div>

   <%= will_paginate @episode %>

 <script>
    $(document).ready(function(){
      $("#jquery_jplayer_1").jPlayer({
        ready: function () {
          $(this).jPlayer("setMedia", {
            mp3: "<%= @episode.mp3.url>",
          });
        },
        swfPath: "/js",
        supplied: "mp3"
      });
    });
  </script>

app/views/layouts/_header.html.erb
 <header id="main_header" class="cf">
 <div class="wrapper_wide">
 <%= link_to "Hub Mentors", root_path, id:"logo" %>

  <nav>
    <ul>
    <% unless mentor_signed_in? %>
    <li><%= link_to "Mentors", mentors_path %></li>
    <li><%= link_to "Hubs", hubs_path %></li>
    <li><%= link_to "Start Mentoring", new_mentor_registration_path %></li>
    <li><%= link_to "Sign In", new_mentor_session_path %></li>
    <% else %>
    <li><%= link_to "Dashboard", root_path %></li>
    <li><%= link_to "Mentors", mentors_path %></li>
    <li><%= link_to "Hubs", hubs_path %></li>
    <li><%= link_to "Plan Trip", schedules_path %></li>
    <li><%= link_to "Contact", new_contact_path %></li>         
    <li><%= link_to "Sign Out", destroy_mentor_session_path, method: :delete %></li>
    <% end %>
   </ul>

 </nav>
 </div>
 </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hub Mentors</title>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,400italic,700,700italic' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <% if notice %>
      <div id="notice_wrapper">
       <p class="notice"><%= notice %></p>
      </div>
    <% elsif alert %>
      <div id="notice_wrapper">
       <p class="alert"><%= alert %></p>
      </div>
    <% end %>

 <% unless current_page?(root_path) %>
  <%= render 'layouts/header' %>
 <% end %>
<%= yield %>
 <script>
$(document).ready(function(){
  setTimeout(function(){
   $('#notice_wrapper').fadeOut("slow",function(){
    $this.remove();
    }):
  }, 3500);
});
 </script>
</body>
</html>

app/views/mentors/dashboard.html.erb
<%= render 'layouts/header' %>

  <div id="podcast_show">
   <div id="show_banner">
    <div class="wrapper_skinny">
       <h1><%= @mentor.title %> Dashboard</h1>
    </div>
   </div>
   <div id="links">
     <div class="wrapper_skinny">
      <ul>
        <li><%= link_to "Posts", root_path %></li>
        <li><%= link_to "New Post", new_mentor_episode_path(@mentor, @episode) %></li>
        <li><% link_to "Account Settings", edit_mentor_registration_path %></li>
        <li><%= link_to "View Mentor", mentor_path(current_mentor) %></li>
      </ul>
     </div>
    </div>

     <div id="episodes">
        <div class="wrapper_skinny">
          <ul class="cf">
            <% @episodes.each do |episode| %>
            <li class="cf">
              <div class="episode_thumbnail">
                 <a href="<%= link_to episode.title, mentor_episode_path(@mentor, episode)  %>">
                  <%= image_tag episode.episode_thumbnail.url(:medium) %>
                 </a>
              </div>
              <div class="episode_overview">
                <h2><%= link_to episode.title, mentor_episode_path(@mentor, episode) %></h2> 	
                 <p class="description">
                   <%= truncate(episode.description, length:160) %>
                 </p>
               <div class="authorized_links">
                 <%= link_to "Edit", edit_mentor_episode_path(@mentor, episode) %>
                 <%= link_to "Delete", mentor_episode_path(@mentor, episode), method: :delete, data: {confirm: "Are you sure?"} %>         
               </div>
              </div>	
            </li>
           <% end %>
          </ul>
        </div>
     </div>
    </div>

  </div>

app/views/mentors/index.html.erb
<div id="banner" class="podcasts_banner">
    <h1 class="highlight">Explore a mentor's story.</h1>
</div>

 <div id="podcasts" class="cf">
  <div class="wrapper">

 <div id="breadcrumb">
 <ul>
          <li><%= link_to "All Mentors", mentors_path, class:"mentorlist" %></li>
          <% Category.all.each do |category| %>
          <li class="subscribe_link"><%= link_to category.name, mentors_path(category: category.name ), class:"mentorlist" %></li>
          <% end %>
 </ul>
 </div>

   <ul class="cf">
   <% @mentors.each do |mentor| %>
    <% link_to mentor do %>
    <li>
     <%= image_tag mentor.thumbnail.url(:medium) %>
      <div class="podcast_overview">
      <h2><%= mentor.title %></h2>
      <h4><%= mentor.category %></h4> 
       <p class="episode_count"><% @episodes.count %></p>
      </div>
    </li>
   <% end %>
  <% end %>
  </ul>
   <%= will_paginate @mentor %>
   </div>
 </div>

app/views/mentors/show.html.erb
<div id="podcast_show">
     <div id="show_banner">
     	<div class="wrapper_skinny">
         <h1><%= @mentor.title %></h1>
	       <p class="description"><%= @mentor.description %></p>
               <% unless @mentor.blog.blank? %>
	        <a href="<%= @mentor.blog %>" class="subscribe_link">blog</a>
               <% end %>
               <% unless @mentor.facebook.blank? %>
                <a href="<%= @mentor.facebook %>" class="subscribe_link">facebook</a>
               <% end %>

               <% unless @mentor.twitter.blank? %>
                <a href="<%= @mentor.twitter %>" class="subscribe_link">twitter</a>
               <% end %>

               <% unless @mentor.linkedin.blank? %>
                <a href="<%= @mentor.linkedin %>" class="subscribe_link">linkedin</a>
               <% end %>
     	</div>      
     </div>

     <div id="breadcrumb">
      <%= link_to mentors_path do %>
        All podcasts
       <span>/</span>
        <%= @mentor.category %>
        <span>/</span>
        <%= @mentor.category %>
      <% end %>
     </div>

     <div id="episodes">
        <div class="wrapper_skinny">
          <ul class="cf">
           <% @episodes.each do |episode| %>
            <li class="cf">
              <div class="episode_thumbnail">
                 <a href="#">
                  <%= image_tag episode.episode_thumbnail.url(:medium) %>
                 </a>
              </div>
              <div class="episode_overview">
                <h2><%= link_to episode.title, mentor_episode_path(@mentor, episode) %></h2> 	
                 <p class="description">
                 <% truncate(episode.description, length: 160) %>
                 </p>
              </div>	
            </li>
           <% end %>
          </ul>
        </div>
     </div>
    </div>

app/views/welcome/index.html.erb
  <div id="background">
   <header class="cf">
  	<div class="wrapper_wide">
 	<a href="#" id="logo">Hub Mentors</a>
  <nav>
 	<ul>
	<li><%= link_to "Explore", mentors_path %></li>
        <li><%= link_to "Sign In", new_mentor_session_path %></li>
        <li><%= link_to "Start Mentoring", new_mentor_registration_path %></li>
        </ul>
  </nav>
  </div>
   </header>
   <div class="wrapper_skinny">
    <h1>Mentor the World <br>- and catch a holiday!</h1>
    <%= link_to "Start Mentoring", new_mentor_registration_path, class: "button button_highlight" %>
    <%= link_to "How it works", how_index_path, class: "button button_white" %>
  </div>
  </div>